language: node_js
node_js: 8

matrix:
  include:
    - language: objective-c
      osx_image: xcode11
      env:
        global:
          - NODE_VERSION=stable

      install:
        - brew tap wix/brew
        - brew install applesimutils
        - npm install -g detox-cli
        - npm install -g react-native-cli
      script:
        - cd SampleApps/DetoxApp
        - npm install --force
        - npm install react-native-appsflyer --save
        - detox build --configuration android
        - detox test --configuration android --cleanup
